#include "app_user.h"

/* generated by fbt from .png files in images folder */

int32_t testing_app_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm testing_app!");

    return 0;
}
