#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <testing_app_icons.h>

int32_t testing_app_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm testing_app!");

    return 0;
}
