name: "FAP: Build and Release"

on:
  push:
    tags:
      - 'v*'
    branches:
      - '**'

  pull_request:

jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    name: "ufbt: Build App"

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=Dev-${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        env:
          EXTRA_CFLAGS: '-DFAP_APP_VERSION=\"${{ env.TAG_NAME }}\"'
        with:
          sdk-index-url: https://up.unleashedflip.com/directory.json
          sdk-channel: release
          app-dir: ./EthernetAppDemo/

      - name: Rename FAP Artifact
        id: rename-fap
        run: |
          ORIGINAL="${{ steps.build-app.outputs.fap-artifacts }}"
          RENAMED="${ORIGINAL%.fap}_${{ env.TAG_NAME }}.fap"

          mv "$ORIGINAL" "$RENAMED"

          echo "RENAMED_FAP=$RENAMED" >> $GITHUB_ENV

      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ env.TAG_NAME }}
          path: ${{ env.RENAMED_FAP }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}

          body_path: release-notes/${{ env.TAG_NAME }}.md

          files: |
            ${{ env.RENAMED_FAP }}

          draft: false
          prerelease: false
          generate_release_notes: false
